# Default Configuration File

#Determine if MySql is used
MySql: false
MySqlHost: localhost
MySqlPort: 3306
MySqlUsername: root
MySqlPassword: password
MySqlDatabase: minecraft

# List of words you want blocked from chat
badWordsTier1:
  - 'exampleword1'
  - 'example_word2' # use '_' instead of spaces.

  
# List of groups and their properties(Group names MUST be the same as 
# your permission groups)
# Possible colors: black, dark blue, dark green, teal, dark red,
#     purple, gold, gray, dark gray, blue, lime green, aqua, red, pink,
#     yellow, white.

Groups:
  default:
    groupNameColor: gray
    groupBold: false
    nameColor: white
    nameBold: false
    textColor: white
    textBold: false
    
# Have GChat controls the colors of the names in the tab player list.
# This means it will have the colors of the names in that list associated with
# the color of their name in chat
TabPlayerList: true

# How many capital letters are allowed before the message is converted to all
# lower case
CapsAllowed: 4