name: GChat
description: Make chat into JSON awesomeness and more
author: FearMig
website: www.github.com/fearmig
version: 1.1
main: org.mig.gchat.utils.GChat

softdepend: [Essentials,Towny]

commands:
  gchat:
    description: TownyPatch commands
    aliases: [gc]
  tc:
    description: Go into Town chat mode.
  g:
    description: Go into Global chat mode.
  nc:
    description: /Go into Nation chat mode.
  ac:
    description: /Go into Admin chat mode.