name: GChatTowny
description: Make Towny chat JSON
author: FearMig
website: www.github.com/fearmig
version: 1.0
main: org.mig.gchattowny.tPatch

depend: [Essentials, Towny]

commands:
  gchat:
    description: TownyPatch commands